# Generated by Django 4.0.4 on 2022-05-21 07:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(help_text='Descriptive name for this album.', max_length=120, unique=True)),
                ('slug', models.CharField(help_text='Slugified version of this album title for use in URLs.', max_length=16, unique=True)),
                ('about', models.TextField(blank=True, help_text='Optional additional information this album')),
                ('order', models.IntegerField(blank=True, help_text='Controls ordering of album thumbnails on homepage', null=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimplePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(help_text='Title for this page', max_length=120)),
                ('body', models.TextField(help_text='General purpose text area')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('flickr_id', models.BigIntegerField(help_text='Unique Flickr ID for each image', unique=True)),
                ('title', models.CharField(blank=True, help_text='Title auto-copied from Flickr title, can be overridden', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Description auto-copied from Flickr description, can be overridden')),
                ('album_order', models.IntegerField(blank=True, db_index=True, default=0, help_text='Controls ordering of image within albums, and next/prev links.')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.album')),
            ],
            options={
                'ordering': ['album_order'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='cat_thumb',
            field=models.ForeignKey(blank=True, help_text='Each album should be associated with one of the images in that album, to be used in web layouts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_thumb', to='gallery.image', verbose_name='Album Thumbnail'),
        ),
    ]
