# Generated by Django 4.0.4 on 2022-05-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepage',
            name='title',
            field=models.CharField(blank=True, help_text='Auto-copied from Flickr title, can be overridden', max_length=120),
        ),
    ]
