# Generated by Django 4.0.4 on 2022-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_simplepage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='taken',
            field=models.DateTimeField(blank=True, help_text='Datetime when image was captured, as reported by Flickr API.', null=True),
        ),
    ]
