# Generated by Django 4.0.4 on 2022-05-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_imagepage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorypage',
            name='slug',
            field=models.CharField(blank=True, help_text='Slugified version of this category title.', max_length=16, null=True),
        ),
    ]
