# Generated by Django 4.0.4 on 2022-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_categorypage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypage',
            name='slug',
            field=models.CharField(default='foo', help_text='Slugified version of this category title.', max_length=16, unique=True),
            preserve_default=False,
        ),
    ]
