# Generated by Django 4.0.4 on 2022-05-27 07:35

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_taken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='image',
            name='image_api_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Stores full image detail response from Flickr getInfo API.'),
        ),
    ]
