# Generated by Django 4.0.4 on 2022-05-13 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_categorypage_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryPage',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='ImagePage',
            new_name='Image',
        ),
    ]
