# Generated by Django 4.0.4 on 2022-05-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_rename_categorypage_category_rename_imagepage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, help_text='Description auto-copied from Flickr title, can be overridden'),
        ),
        migrations.AlterField(
            model_name='category',
            name='about',
            field=models.TextField(help_text='Optional additional information this category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(help_text='Slugified version of this category title for use in URLs.', max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Descriptive name for this category.', max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='flickr_id',
            field=models.IntegerField(help_text='Unique Flickr ID for each image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, help_text='Title auto-copied from Flickr title, can be overridden', max_length=120),
        ),
    ]
