# Generated by Django 4.0.4 on 2022-05-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='about',
            field=models.TextField(blank=True, help_text='Optional additional information this category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='flickr_id',
            field=models.BigIntegerField(help_text='Unique Flickr ID for each image'),
        ),
    ]
