# Generated by Django 4.0.4 on 2022-05-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_category_about_alter_image_flickr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album_order',
            field=models.IntegerField(default=1, help_text='Controls ordering of image within albums, and next/prev links.'),
            preserve_default=False,
        ),
    ]
