# Generated by Django 4.0.4 on 2022-05-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_image_album_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_thumb',
            field=models.ForeignKey(blank=True, help_text='Each category should be associated with one of the images in that category, to be used in web layouts.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.image', verbose_name='Category Thumbnail'),
        ),
    ]
