# Generated by Django 4.0.4 on 2022-05-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0010_category_cat_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album_order',
            field=models.IntegerField(blank=True, help_text='Controls ordering of image within albums, and next/prev links.', null=True),
        ),
    ]
