# Generated by Django 4.0.4 on 2022-05-17 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_alter_image_album_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='flickr_id',
            field=models.BigIntegerField(help_text='Unique Flickr ID for each image', unique=True),
        ),
    ]
