# Generated by Django 4.0.4 on 2022-05-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0012_alter_image_flickr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, help_text='Controls ordering of category thumbnails on homepage', null=True),
        ),
    ]
