# Generated by Django 4.0.4 on 2022-05-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0015_album_remove_image_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gallery.album'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='cat_thumb',
            field=models.ForeignKey(blank=True, help_text='Each album should be associated with one of the images in that album, to be used in web layouts.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_thumb', to='gallery.image', verbose_name='Album Thumbnail'),
        ),
    ]
