# Generated by Django 4.0.4 on 2022-05-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0016_image_album_alter_album_cat_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['album_order']},
        ),
        migrations.AlterField(
            model_name='image',
            name='album_order',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Controls ordering of image within albums, and next/prev links.', unique=True),
        ),
    ]
