# Generated by Django 4.0.4 on 2022-05-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0017_alter_image_options_alter_image_album_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album_order',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='Controls ordering of image within albums, and next/prev links.'),
        ),
    ]
